fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
          rules:
              - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        default_engine: twig
        view_response_listener: 'force'
        serialize_null: true
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
    serializer:
        serialize_null: true